# Marp convertion configuration
author: Baptiste Mehat

inputDir: src/
output: build/

theme: uncover

# Convert slide deck notes into a text file
notes: true
# Add presenter notes to PDF as annotations
pdfNotes: true

pdf: true
